version: '3.4'

services:
  database:
    container_name: database
    image: postgres:latest
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senhaS3creta
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senhaS3creta
    ports:
      - 27017:27017
    networks:
      - app-network
  
  ftp:
    image: bogem/ftp
    restart: always
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    env_file:
    - .env
    volumes:
      - ./assets-data:/home/vsftpd
    networks:
      - app-network
  
  file-server:
    image: nginx:alpine
    ports:
      - 8989:80
    volumes:
      - ./assets-data:/usr/share/nginx/html
    networks:
      - app-network
  
  redis:
    image: redis:latest
    hostname: localhost
    ports:
        - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
