name: DEVELOPMENT GCP - CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: development
    env:
      PROJECT_ID: edueduescola-teste
      IMAGE_NAME: eduedu-escola-backend
      REGISTRY_NAME: eduedu-escola-backend-development
      REGISTRY_PREFIX: us-east1-docker.pkg.dev
      ARG_FIRESTORE_READ_SERVICEACCOUNT: ${{ secrets.ARG_FIRESTORE_READ_SERVICEACCOUNT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build Docker Image
        run: |
          docker build \
          --build-arg ARG_FIRESTORE_READ_SERVICEACCOUNT=${{ secrets.ARG_FIRESTORE_READ_SERVICEACCOUNT }} \
          -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker $REGISTRY_PREFIX --quiet

      - name: Push Docker Image to Artifact Registry
        run: |
          docker tag $IMAGE_NAME:latest $REGISTRY_PREFIX/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{ github.run_number }}
          docker push $REGISTRY_PREFIX/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{ github.run_number }}

  deploy:
    name: Deploy New Revision
    needs: build-push
    runs-on: ubuntu-latest
    environment: development
    env:
      PROJECT_ID: edueduescola-teste
      IMAGE_NAME: eduedu-escola-backend
      REGISTRY_NAME: eduedu-escola-backend-development
      REGISTRY_PREFIX: us-east1-docker.pkg.dev
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      RABBITMQ_URI: ${{ secrets.RABBITMQ_URI }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: 'dev-eduedu-escola-backend'
          image: '${{ env.REGISTRY_PREFIX }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}'
          region: us-central1
          env_vars: |
            DATABASE_URL=${{ env.DATABASE_URL }}
            MONGO_URI=${{ env.MONGO_URI }}
            MONGO_USER=${{ env.MONGO_USER }}
            MONGO_PASSWORD=${{ env.MONGO_PASSWORD }}
            RABBITMQ_URI=${{ env.RABBITMQ_URI }}

      - name: Check Deployment Status
        id: deployment
        run: |
          echo "Deployment Status: ${{ steps.deploy.outputs.status }}"

      - name: Display App URL
        if: steps.deployment.outputs.status == 'success'
        run: |
          echo "App URL: ${{ steps.deploy.outputs.url }}"

      - name: Deployment Rejected
        if: steps.deployment.outputs.status == 'failure'
        run: |
          echo "Deployment was rejected or did not satisfy protection rules."