---
name: DEVELOPMENT GCP - CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: development
    env:
      IMAGE_NAME: eduedu-escola-backend-development
      PROJECT_ID: edueduescola-teste
      REGISTRY_PREFIX: us-east1-docker.pkg.dev
      REGISTRY_NAME: eduedu-escola-backend-development

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker $REGISTRY_PREFIX --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest $REGISTRY_PREFIX/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{github.run_number}}
        docker push $REGISTRY_PREFIX/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{github.run_number}}

    - name: Send Build Error Message
      if: failure()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#ff0000"
        username: "GitHub Bot"
        avatar_url: https://i.imgur.com/Kvn45ev.png
        message: Backend | Algo de errado não está certo com o código... | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    outputs:
      git-tag: ${{ steps.increment-git-tag.outputs.git-tag }}

  deploy:
    name: Deploy New Revision
    needs: build-push
    runs-on: ubuntu-latest
    environment: development
    env:
      IMAGE_NAME: eduedu-escola-backend-development
      PROJECT_ID: edueduescola-teste
      REGISTRY_PREFIX: us-east1-docker.pkg.dev
      REGISTRY_NAME: eduedu-escola-backend-development
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      RABBITMQ_URI: ${{ secrets.RABBITMQ_URI }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

    - name: Deploy
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'dev-eduedu-escola-backend'
        image: '${{ env.REGISTRY_PREFIX }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}'
        region: us-central1
        env_vars: |-
          DATABASE_URL=${{ env.DATABASE_URL }}
          MONGO_URI=${{ env.MONGO_URI }}
          MONGO_USER=${{ env.MONGO_USER }}
          MONGO_PASSWORD=${{ env.MONGO_PASSWORD }}
          RABBITMQ_URI=${{ env.RABBITMQ_URI }}

    - name: 'App URL'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
    
    - name: Send Success Message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#00ba55"
        username: "GitHub Bot"
        avatar_url: https://i.imgur.com/Kvn45ev.png
        message: Backend | Commit '${{ github.event.head_commit.message }}' disponível no ambiente de DEV | ${{ secrets.APP_URL }}
