name: Publicação de Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag da release que será gerada"
        required: true

env:
  PROJECT_ID: eduedu-plus-open-source-prd
  REGION: southamerica-east1
  GAR_LOCATION: southamerica-east1-docker.pkg.dev/eduedu-plus-open-source-prd/eduedu-plus-setup/eduedu-plus-backend

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    environment: os-prd
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}:${{ github.event.inputs.tag }}
        working-directory: .

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}:${{ github.event.inputs.tag }}
