---
name: Publicação de Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag da release que será gerada'
        required: true

jobs:
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: staging
    env:
      IMAGE_NAME: eduedu-escola-backend-main
      PROJECT_ID: edueduescola-teste
      REGISTRY_PREFIX: us-east1-docker.pkg.dev
      ARG_FIRESTORE_READ_SERVICEACCOUNT: ${{ secrets.ARG_FIRESTORE_READ_SERVICEACCOUNT }}
      REGISTRY_SETUP_REPOSITORY: ${{ secrets.REGISTRY_SETUP_REPOSITORY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag }}
    
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Build Docker Image
      run: |-
        docker build \
        --build-arg ARG_FIRESTORE_READ_SERVICEACCOUNT=${{ secrets.ARG_FIRESTORE_READ_SERVICEACCOUNT }} \
        -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker $REGISTRY_PREFIX --quiet

    - name: Push Docker Image to Setup
      run: |-
        docker tag $IMAGE_NAME:latest $REGISTRY_SETUP_REPOSITORY:${{ github.event.inputs.tag }}
        docker push $REGISTRY_SETUP_REPOSITORY:${{ github.event.inputs.tag }}
